# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yysElf.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 390)
        MainWindow.setMinimumSize(QtCore.QSize(650, 390))
        MainWindow.setMaximumSize(QtCore.QSize(650, 390))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_topspace = QtWidgets.QVBoxLayout()
        self.verticalLayout_topspace.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_topspace.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_topspace.setObjectName("verticalLayout_topspace")
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_topspace.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_topspace)
        self.main_space = QtWidgets.QFrame(self.centralwidget)
        self.main_space.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_space.setLineWidth(4)
        self.main_space.setMidLineWidth(4)
        self.main_space.setObjectName("main_space")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_space)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Layout_player = QtWidgets.QVBoxLayout()
        self.Layout_player.setContentsMargins(10, 10, 10, 10)
        self.Layout_player.setObjectName("Layout_player")
        self.space_player_1 = QtWidgets.QFrame(self.main_space)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.space_player_1.setFont(font)
        self.space_player_1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.space_player_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.space_player_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.space_player_1.setLineWidth(4)
        self.space_player_1.setMidLineWidth(4)
        self.space_player_1.setObjectName("space_player_1")
        self.label_player_1 = QtWidgets.QLabel(self.space_player_1)
        self.label_player_1.setGeometry(QtCore.QRect(10, 10, 40, 20))
        self.label_player_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_player_1.setWordWrap(False)
        self.label_player_1.setIndent(-1)
        self.label_player_1.setOpenExternalLinks(False)
        self.label_player_1.setObjectName("label_player_1")
        self.hwd_comboBox_1 = QtWidgets.QComboBox(self.space_player_1)
        self.hwd_comboBox_1.setGeometry(QtCore.QRect(10, 40, 70, 20))
        self.hwd_comboBox_1.setObjectName("hwd_comboBox_1")
        self.is_captain_1 = QtWidgets.QCheckBox(self.space_player_1)
        self.is_captain_1.setGeometry(QtCore.QRect(120, 10, 70, 20))
        self.is_captain_1.setObjectName("is_captain_1")
        self.is_catch_inout_1 = QtWidgets.QCheckBox(self.space_player_1)
        self.is_catch_inout_1.setGeometry(QtCore.QRect(120, 40, 70, 20))
        self.is_catch_inout_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.is_catch_inout_1.setTristate(False)
        self.is_catch_inout_1.setObjectName("is_catch_inout_1")
        self.call_thumbnail_1 = QtWidgets.QPushButton(self.space_player_1)
        self.call_thumbnail_1.setGeometry(QtCore.QRect(350, 60, 75, 23))
        self.call_thumbnail_1.setObjectName("call_thumbnail_1")
        self.is_autoReady_1 = QtWidgets.QCheckBox(self.space_player_1)
        self.is_autoReady_1.setGeometry(QtCore.QRect(120, 70, 70, 20))
        self.is_autoReady_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.is_autoReady_1.setTristate(False)
        self.is_autoReady_1.setObjectName("is_autoReady_1")
        self.is_autoTryEvent_1 = QtWidgets.QCheckBox(self.space_player_1)
        self.is_autoTryEvent_1.setGeometry(QtCore.QRect(220, 10, 90, 20))
        self.is_autoTryEvent_1.setObjectName("is_autoTryEvent_1")
        self.is_autoYeYuanHuo_1 = QtWidgets.QCheckBox(self.space_player_1)
        self.is_autoYeYuanHuo_1.setGeometry(QtCore.QRect(220, 40, 90, 20))
        self.is_autoYeYuanHuo_1.setObjectName("is_autoYeYuanHuo_1")
        self.refresh_list_1 = QtWidgets.QPushButton(self.space_player_1)
        self.refresh_list_1.setGeometry(QtCore.QRect(25, 70, 40, 20))
        self.refresh_list_1.setObjectName("refresh_list_1")
        self.Layout_player.addWidget(self.space_player_1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.Layout_player.addItem(spacerItem1)
        self.space_player_2 = QtWidgets.QFrame(self.main_space)
        self.space_player_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.space_player_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.space_player_2.setLineWidth(4)
        self.space_player_2.setMidLineWidth(4)
        self.space_player_2.setObjectName("space_player_2")
        self.label_player_2 = QtWidgets.QLabel(self.space_player_2)
        self.label_player_2.setGeometry(QtCore.QRect(10, 10, 40, 20))
        self.label_player_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_player_2.setWordWrap(False)
        self.label_player_2.setIndent(-1)
        self.label_player_2.setOpenExternalLinks(False)
        self.label_player_2.setObjectName("label_player_2")
        self.hwd_comboBox_2 = QtWidgets.QComboBox(self.space_player_2)
        self.hwd_comboBox_2.setGeometry(QtCore.QRect(10, 40, 70, 20))
        self.hwd_comboBox_2.setObjectName("hwd_comboBox_2")
        self.is_captain_2 = QtWidgets.QCheckBox(self.space_player_2)
        self.is_captain_2.setGeometry(QtCore.QRect(120, 10, 70, 20))
        self.is_captain_2.setObjectName("is_captain_2")
        self.is_catch_inout_2 = QtWidgets.QCheckBox(self.space_player_2)
        self.is_catch_inout_2.setGeometry(QtCore.QRect(120, 40, 70, 20))
        self.is_catch_inout_2.setTristate(False)
        self.is_catch_inout_2.setObjectName("is_catch_inout_2")
        self.call_thumbnail_2 = QtWidgets.QPushButton(self.space_player_2)
        self.call_thumbnail_2.setGeometry(QtCore.QRect(350, 60, 75, 23))
        self.call_thumbnail_2.setObjectName("call_thumbnail_2")
        self.is_autoReady_2 = QtWidgets.QCheckBox(self.space_player_2)
        self.is_autoReady_2.setGeometry(QtCore.QRect(120, 70, 70, 20))
        self.is_autoReady_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.is_autoReady_2.setTristate(False)
        self.is_autoReady_2.setObjectName("is_autoReady_2")
        self.is_autoTryEvent_2 = QtWidgets.QCheckBox(self.space_player_2)
        self.is_autoTryEvent_2.setGeometry(QtCore.QRect(220, 10, 90, 20))
        self.is_autoTryEvent_2.setObjectName("is_autoTryEvent_2")
        self.is_autoYeYuanHuo_2 = QtWidgets.QCheckBox(self.space_player_2)
        self.is_autoYeYuanHuo_2.setGeometry(QtCore.QRect(220, 40, 90, 20))
        self.is_autoYeYuanHuo_2.setObjectName("is_autoYeYuanHuo_2")
        self.refresh_list_2 = QtWidgets.QPushButton(self.space_player_2)
        self.refresh_list_2.setGeometry(QtCore.QRect(25, 70, 40, 20))
        self.refresh_list_2.setObjectName("refresh_list_2")
        self.Layout_player.addWidget(self.space_player_2)
        self.Layout_player.setStretch(0, 1)
        self.Layout_player.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.Layout_player)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.main_space)
        self.widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(120, 0))
        self.widget.setObjectName("widget")
        self.is_autoRefuseGoldOffer = QtWidgets.QCheckBox(self.widget)
        self.is_autoRefuseGoldOffer.setGeometry(QtCore.QRect(20, 20, 90, 20))
        self.is_autoRefuseGoldOffer.setMinimumSize(QtCore.QSize(70, 20))
        self.is_autoRefuseGoldOffer.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.is_autoRefuseGoldOffer.setCheckable(True)
        self.is_autoRefuseGoldOffer.setChecked(True)
        self.is_autoRefuseGoldOffer.setTristate(False)
        self.is_autoRefuseGoldOffer.setObjectName("is_autoRefuseGoldOffer")
        self.auto_yeyuanhuo = QtWidgets.QCheckBox(self.widget)
        self.auto_yeyuanhuo.setEnabled(False)
        self.auto_yeyuanhuo.setGeometry(QtCore.QRect(20, 70, 90, 20))
        self.auto_yeyuanhuo.setMinimumSize(QtCore.QSize(70, 20))
        self.auto_yeyuanhuo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.auto_yeyuanhuo.setChecked(False)
        self.auto_yeyuanhuo.setTristate(False)
        self.auto_yeyuanhuo.setObjectName("auto_yeyuanhuo")

        self.back_button = QtWidgets.QPushButton(self.widget)
        self.back_button.setEnabled(True)
        self.back_button.setGeometry(QtCore.QRect(40, 30, 1, 1))
        self.back_button.setObjectName("back_button")
        self.back_button.setShortcut("Ctrl+F2")

        self.go_button = QtWidgets.QPushButton(self.widget)
        self.go_button.setEnabled(True)
        self.go_button.setGeometry(QtCore.QRect(40, 30, 1, 1))
        self.go_button.setObjectName("go_button")
        self.go_button.setShortcut("Ctrl+F1")

        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.main_space)
        self.verticalLayout_bottomspace = QtWidgets.QVBoxLayout()
        self.verticalLayout_bottomspace.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_bottomspace.setObjectName("verticalLayout_bottomspace")
        spacerItem2 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_bottomspace.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.verticalLayout_bottomspace)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 23))
        self.menubar.setToolTipDuration(-1)
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_property = QtWidgets.QAction(MainWindow)
        self.action_property.setObjectName("action_property")
        self.action_hwdwatcher = QtWidgets.QAction(MainWindow)
        self.action_hwdwatcher.setObjectName("action_hwdwatcher")
        self.action_thumbnail = QtWidgets.QAction(MainWindow)
        self.action_thumbnail.setObjectName("action_thumbnail")
        self.menuSetting.addAction(self.action_property)
        self.menuTools.addAction(self.action_hwdwatcher)
        self.menuTools.addAction(self.action_thumbnail)
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "不孤独的夏目"))
        self.label_player_1.setText(_translate("MainWindow", "窗口1："))
        self.is_captain_1.setText(_translate("MainWindow", "队长"))
        self.is_catch_inout_1.setText(_translate("MainWindow", "响应返回"))
        self.call_thumbnail_1.setText(_translate("MainWindow", "唤起摸鱼器"))
        self.is_autoReady_1.setText(_translate("MainWindow", "自动准备"))
        self.is_autoTryEvent_1.setText(_translate("MainWindow", "自动挑战活动"))
        self.is_autoYeYuanHuo_1.setText(_translate("MainWindow", "自动业原火"))
        self.refresh_list_1.setText(_translate("MainWindow", "刷新"))
        self.label_player_2.setText(_translate("MainWindow", "窗口2："))
        self.is_captain_2.setText(_translate("MainWindow", "队长"))
        self.is_catch_inout_2.setText(_translate("MainWindow", "响应返回"))
        self.call_thumbnail_2.setText(_translate("MainWindow", "唤起摸鱼器"))
        self.is_autoReady_2.setText(_translate("MainWindow", "自动准备"))
        self.is_autoTryEvent_2.setText(_translate("MainWindow", "自动挑战活动"))
        self.is_autoYeYuanHuo_2.setText(_translate("MainWindow", "自动业原火"))
        self.refresh_list_2.setText(_translate("MainWindow", "刷新"))
        self.is_autoRefuseGoldOffer.setText(_translate("MainWindow", "抢勾协"))
        self.auto_yeyuanhuo.setText(_translate("MainWindow", "队长业原火"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.action_property.setText(_translate("MainWindow", "属性"))
        self.action_hwdwatcher.setText(_translate("MainWindow", "窗口查看器"))
        self.action_thumbnail.setText(_translate("MainWindow", "摸鱼管理器"))
